version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - my_python_template_2_DB__uri=postgresql://postgres:postgres@db:5432/my_python_template_2
      - my_python_template_2_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: my_python_template_2_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/my_python_template_2_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=my_python_template_2, my_python_template_2_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
